# Supply the credentials through environment variables. That keeps them out of
# Terraform files, version control and saved plans:
#
#   export IMMOBILIENSCOUT24_CONSUMER_KEY=...
#   export IMMOBILIENSCOUT24_CONSUMER_SECRET=...
#   export IMMOBILIENSCOUT24_ACCESS_TOKEN=...
#   export IMMOBILIENSCOUT24_ACCESS_TOKEN_SECRET=...
provider "immobilienscout24" {
  # "sandbox" (the default) or "production". API keys are issued per environment.
  environment = "sandbox"
}
